# Configuration of the available formats

# Default formatting (if no format is specified)
default_format: "yml"

# Allowed format (specified as file extension for instance 'xml')
allowed_formats: [ yml, yaml ]
