users:
  pattern: /users/
  controller: main.Users.list

user_view:
  pattern: /users/:id
  controller: main.Users.view

user_create:
  pattern: /users/
  controller: main.Users.create
  method: POST
