users:
  pattern: /users
  controller: main.Users.list

user_view:
  pattern: /users/:id
  controller: main.Users.view
  method: GET

user_new:
  pattern: /users/new
  controller: main.Users.new

user_create:
  pattern: /users/create
  controller: main.Users.create
  method: POST

user_edit:
  pattern: /users/:id/edit
  controller: main.Users.edit

user_update:
  pattern: /users/:id/update
  controller: main.Users.update
  method: POST

user_delete:
  pattern: /users/:id/delete
  controller: main.Users.delete
